apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: b-6563a38c-618f-48c0-ab15-46221fdfac9f-certificate
  namespace: b-6563a38c-618f-48c0-ab15-46221fdfac9f
spec:
  secretName: b-6563a38c-618f-48c0-ab15-46221fdfac9f-secret-tls
  commonName: lyna-b.assessify.org
  dnsNames:
  - lyna-b.assessify.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
